/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#dae2fd",
        "primary-container": "#2563eb",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "background": "#0b1326",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "on-primary-container": "#eeefff",
        "secondary-fixed-dim": "#4edea3",
        "on-background": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "surface": "#0b1326",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary": "#002a78",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "inverse-primary": "#0053db",
        "on-secondary-fixed": "#002113",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#283044",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed": "#00174b",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#996100",
        "primary": "#b4c5ff",
        "surface-container-highest": "#2d3449",
        "tertiary": "#ffb95f",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed": "#2a1700",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "on-secondary": "#003824",
        "tertiary-fixed": "#ffddb8",
        "surface-dim": "#0b1326",
        "outline": "#8d90a0",
        "secondary": "#4edea3",
        "on-tertiary": "#472a00",
        "surface-container-low": "#131b2e",
        "outline-variant": "#434655",
        "error-container": "#93000a",
        "on-surface-variant": "#c3c6d7",
        "surface-bright": "#31394d",
        "surface-tint": "#b4c5ff",
        "on-tertiary-container": "#ffeedd",
        "on-primary-fixed-variant": "#003ea8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "lg": "24px",
        "margin-desktop": "32px",
        "sm": "8px",
        "xs": "4px",
        "gutter": "20px",
        "xl": "40px",
        "md": "16px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Space Grotesk"],
        "mono-data": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Space Grotesk"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Space Grotesk"]
      },
      "fontSize": {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
